---
application:
  name: "md-renamebot"
  project: "mdrenamebot"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "renamebotsj"
  version: "8.0"
routers:
- name: "main-filerenamebot"
  routes:
  - application_name: "md-renamebot"
    paths:
    - "/*"
